- name: Docker
  hosts: localhost
  vars_prompt:
          - name: cont_name
            prompt: "Enter name of container "
            private: no
  tasks:
          - name: Installing Docker SDK
            block:
              - command: pip3 show docker-py
            rescue:
             - pip:
                name: docker-py        
          - name: Start docker service
            service:
               name: "docker"
               state: started
               enabled: yes
            register: b
          - debug:
                var: b.state

          - name: Put SELinux in permissive mode
            ansible.posix.selinux:
                          policy: targeted
                          state: permissive
            register: c
          - debug:
                  var: c.state

          - name: Pull an image
            community.general.docker_image:
                               name: simrankukareja/ssh
                               source: pull
                               state: present
            register: d
          - debug:
                  var: d.image

          - name: Launching A Docker Container
            community.general.docker_container:
                         name: "{{ cont_name }}"
                         image: simrankukareja/ssh
                         state: started
                         interactive: yes
                         detach: yes
                         tty: yes
                         ports:
                            - "8081:80"
            register: e
          - debug:
                   var: e

          - name: Retrive IP of running Container
            community.general.docker_container_info:
                     name: "{{ cont_name }}"
            register: f
          - debug:
                   var: f.container.NetworkSettings.IPAddress  

          - name: Update Inventory file
            blockinfile:
                     path: /etc/hosts.txt
                     block: |
                             [docker]
                             "{{ f['container']['NetworkSettings']['IPAddress'] }}" ansible_ssh_user=root ansible_ssh_pass=simran  ansible_connection=ssh

            register: g
          - debug:
                   var: g.msg


