- name: Dynamic Docker Configuration
  hosts: localhost
  vars_prompt:
          - name: cont_name
            prompt: "Enter name of container "
            private: no
          - name: image_name
            prompt: "Enter name of image "
            private: no
          - name: tag
            prompt: "Enter tag name "
            private: no
  tasks:
          - name: Installing Docker SDK
            block:
              - command: pip3 show docker-py
            rescue:
             - pip:
                name: docker-py        
          - name: Start docker service
            service:
               name: "docker"
               state: started
               enabled: yes
            register: b
          - debug:
                var: b.state

          - name: Put SELinux in permissive mode
            ansible.posix.selinux:
                    policy: targeted
                    state: permissive
            register: c
          - debug:
                  var: c.state

          - name: Create image with docker file
            community.general.docker_image:
                    name: "{{ image_name }}"
                    build:
                            path: "/dws/"
                    tag: "{{ tag }}"
                    source: build
            register: r
          - debug:
                  var: r

          - name: Launching A Docker Container
            command: docker run -itd --name {{ cont_name }} -p 2020:22 {{ image_name }}:{{ tag }} 
            register: e
          - debug:
                   var: e

          - name: Retrive IP of running Container
            community.general.docker_container_info:
                     name: "{{ cont_name }}"
            register: f
          - debug:
                   var: f.container.NetworkSettings.IPAddress  

          - name: Update Inventory file
            blockinfile:
                     path: /etc/hosts.txt
                     block: |
                             [docker]
                             {{ f['container']['NetworkSettings']['IPAddress'] }} ansible_ssh_user=root ansible_ssh_pass=simran  ansible_connection=ssh

            register: g
          - debug:
                   var: g.msg


